apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: prepare-release
  labels:
    app: "artcd"
spec:
  params:
  - name: group
    description: Group name. e.g. openshift-4.9
  - name: assembly
    description: The name of an assembly; must be defined in releases.yml (e.g. 4.9.1)
  - name: date
    description: Expected release date (e.g. 2022-Mar-25)
  - name: package_owner
    description: (Optional) Must be an individual email address; may be anyone who wants random advisory spam
    default: ""
  - name: name
    description: (Optional) When prepare a release from a stream assembly, use this field to specify the release name.
    default: ""
  - name: nightlies
    description: (Optional) When prepare a release from a stream assembly, use this field to specify proposed nightlies for testing and promotion.
    default: ""
  - name: dry_run
    description: If "true", just exercise the steps without actually preparing a release
    default: "false"
  tasks:
    - name: prepare-release
      taskRef:
        name: prepare-release
      params:
      - name: group
        value: "$(params.group)"
      - name: assembly
        value: "$(params.assembly)"
      - name: name
        value: "$(params.name)"
      - name: date
        value: "$(params.date)"
      - name: nightlies
        value: "$(params.nightlies)"
      - name: package_owner
        value: "$(params.package_owner)"
      - name: dry_run
        value: "$(params.dry_run)"
